#!/bin/bash

SNAPSHOT_FILE="$HOME/.archive-system-tar-incremental-snapshot"
SNAPSHOT_TEMP_FILE="${SNAPSHOT_FILE}-new"
LOCK_FILE="$HOME/.archive-system-lock"
VAULT="archive-system"

ARCHIVE_PATHS=(
	"$HOME/src"
)

START_TIME="`date +%s`"

[ -n "$HOSTNAME" ] || HOSTNAME="`hostname`"

die() {
	code="$1"
	shift
	echo "$@"
	echo "Exiting: $code"
	exit "$code"
}

echo "Running \"$0 $@\" @$START_TIME for host $HOSTNAME into vault $VAULT"
echo "Using snapshot file: $SNAPSHOT_FILE"
echo "Archiving paths:"
for path in "${ARCHIVE_PATHS[@]}"; do
	echo -e "\t$path"
done

echo "Acquiring file lock on $LOCK_FILE"
exec 42>> "$LOCK_FILE"
flock -s 42
echo "Lock acquired"

if [ -e "$SNAPSHOT_TEMP_FILE" ]; then
	echo "Warning: $SNAPSHOT_TEMP_FILE already exists"
	[ -f "$SNAPSHOT_TEMP_FILE" ] || die 1 "Existing snapshot temp file is not a regular file"
fi

echo "Creating temporary snapshot file"
cp "$SNAPSHOT_FILE" "$SNAPSHOT_TEMP_FILE" || die 1 "Failed to create snapshot temp file"

ARCHIVE_NAME="${HOSTNAME}-${START_TIME}.tar.gz"
echo "Performing upload of archive $ARCHIVE_NAME"
tar czg "$SNAPSHOT_TEMP_FILE" | glacier archive upload "$VAULT" --name="$ARCHIVE_NAME" - ||
	die 1 "Upload failed."
echo "Upload finished."

mv "$SNAPSHOT_TEMP_FILE" "$SNAPSHOT_FILE" || die "Snapshot move failed"

echo "Archive run complete."
